# Generated by Django 3.2.25 on 2024-11-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='episodes_per_season',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tvshows/'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='seasons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
