# Generated by Django 3.2.25 on 2024-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20241127_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tv_shows/'),
        ),
    ]
